// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvvnfqyhnewojfkvcceq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2dm5mcXlobmV3b2pma3ZjY2VxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NjQyNDgsImV4cCI6MjA2NTM0MDI0OH0.5YcTesE9yehWImBHQTDjYcVqvB-o-4p2qCRic-SgQQE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);